
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this project by running a command like this: '
          '`flutterfire configure --platforms=windows`'
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this project by running a command like this: '
          '`flutterfire configure --platforms=linux`'
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlWunNOQ-soLFXo29MbfFmb-x91moQTKk',
    appId: '1:592140921891:web:0b4d5bd9269bb11a309596',
    messagingSenderId: '592140921891',
    projectId: 'studio-972944250-2fe8d',
    authDomain: 'studio-972944250-2fe8d.firebaseapp.com',
    storageBucket: 'studio-972944250-2fe8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWunNOQ-soLFXo29MbfFmb-x91moQTKk',
    appId: '1:592140921891:android:e9559c5f5b95a828309596',
    messagingSenderId: '592140921891',
    projectId: 'studio-972944250-2fe8d',
    storageBucket: 'studio-972944250-2fe8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWunNOQ-soLFXo29MbfFmb-x91moQTKk',
    appId: '1:592140921891:ios:b5b750186175f56b309596',
    messagingSenderId: '592140921891',
    projectId: 'studio-972944250-2fe8d',
    storageBucket: 'studio-972944250-2fe8d.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWunNOQ-soLFXo29MbfFmb-x91moQTKk',
    appId: '1:592140921891:ios:b5b750186175f56b309596',
    messagingSenderId: '592140921891',
    projectId: 'studio-972944250-2fe8d',
    storageBucket: 'studio-972944250-2fe8d.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
